# Role for flask-monitor: read-only access to pods, services, and configmaps
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-role
  namespace: ashapp
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
